export const wmoCodeMapping = {
  0: "Clear sky",
  1: "Mainly clear", 
  2: "Partly cloudy",
  3: "Overcast",
  4: "Visibility reduced by smoke",
  5: "Haze",
  6: "Widespread dust in suspension",
  7: "Dust or sand raised by wind",
  8: "Well-developed dust or sand whirls",
  9: "Duststorm or sandstorm within sight",
  10: "Mist",
  11: "Patches of shallow fog",
  12: "More or less continuous shallow fog",
  13: "Lightning visible, no thunder heard",
  14: "Precipitation within sight, not reaching ground",
  15: "Precipitation within sight, reaching ground",
  16: "Precipitation within sight, >5km away",
  17: "Thunderstorm, but no precipitation",
  18: "Squalls within sight",
  19: "Funnel cloud within sight",
  20: "Drizzle (not freezing)",
  21: "Rain (not freezing)",
  22: "Snow",
  23: "Rain and snow mixed",
  24: "Freezing drizzle or rain",
  25: "Showers",
  26: "Snow showers or rain and snow mixed",
  27: "Hail or ice pellets",
  28: "Fog or ice fog",
  29: "Thunderstorm (with or without precipitation)",
  30: "Slight or moderate duststorm or sandstorm",
  31: "Slight or moderate duststorm or sandstorm (decreasing)",
  32: "Severe duststorm or sandstorm",
  33: "Severe duststorm or sandstorm (decreasing)",
  34: "Slight or moderate drifting snow",
  35: "Heavy drifting snow",
  36: "Slight or moderate blowing snow",
  37: "Heavy blowing snow",
  38: "Slight or moderate snowstorm (low visibility)",
  39: "Heavy snowstorm (low visibility)",
  40: "Fog at a distance",
  41: "Patches of fog",
  42: "Fog, sky visible (thinning)",
  43: "Fog, sky invisible (thinning)",
  44: "Fog, sky visible (no change)",
  45: "Fog, sky invisible (no change)",
  46: "Fog, sky visible (thickening)",
  47: "Fog, sky invisible (thickening)",
  48: "Fog, depositing rime, sky visible",
  49: "Fog, depositing rime, sky invisible",
  50: "Intermittent light drizzle",
  51: "Continuous light drizzle",
  52: "Intermittent moderate drizzle",
  53: "Continuous moderate drizzle",
  54: "Intermittent dense drizzle",
  55: "Continuous dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  58: "Light drizzle and rain",
  59: "Moderate or heavy drizzle and rain",
  60: "Intermittent light rain",
  61: "Continuous light rain",
  62: "Intermittent moderate rain",
  63: "Continuous moderate rain",
  64: "Intermittent heavy rain",
  65: "Continuous heavy rain",
  66: "Light freezing rain",
  67: "Moderate or heavy freezing rain",
  68: "Light rain or drizzle and snow",
  69: "Moderate or heavy rain or drizzle and snow",
  70: "Intermittent light snow",
  71: "Continuous light snow",
  72: "Intermittent moderate snow",
  73: "Continuous moderate snow",
  74: "Intermittent heavy snow",
  75: "Continuous heavy snow",
  76: "Diamond dust (ice crystals)",
  77: "Snow grains",
  78: "Isolated star-like snow crystals",
  79: "Ice pellets",
  80: "Light rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  83: "Light showers of rain and snow mixed",
  84: "Moderate or heavy showers of rain and snow mixed",
  85: "Light snow showers",
  86: "Moderate or heavy snow showers",
  87: "Light showers of snow pellets or small hail",
  88: "Moderate or heavy showers of snow pellets or small hail",
  89: "Light showers of hail",
  90: "Moderate or heavy showers of hail",
  91: "Thunderstorm with light rain",
  92: "Thunderstorm with moderate or heavy rain",
  93: "Thunderstorm with light snow or rain and snow mixed",
  94: "Thunderstorm with moderate or heavy snow or rain and snow mixed",
  95: "Thunderstorm",
  96: "Thunderstorm with slight hail",
  97: "Thunderstorm with heavy hail",
  98: "Thunderstorm combined with duststorm or sandstorm",
  99: "Severe thunderstorm with tornado"
};

export default wmoCodeMapping;